spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fate
    password: P@ssw0rd
    url: jdbc:mysql://cdb-hhkbssqo.bj.tencentcdb.com:10138/fate?useSSL=false
  batch:
    job:
      enabled: true

  data:
    mongodb:
      host: 62.234.86.166
      port: 27017
      username: tester
      password: password
      authentication-database: test


  #    initialize-schema: always
  rabbitmq:
    addresses: 62.234.86.166:5672
    username: fate
    password: p@ssw0rd
    virtual-host: /
    connection-timeout: 15000s
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 4
        max-concurrency: 12
    publisher-confirms: true
    publisher-returns: true #return 的时候代表消息不可达，设置 broker 不自动删除该消息，
    template:
      mandatory: true